insert into boards	
(board_id,
	name,
	difficulty,
	title,
	description,
	prerequisite,
	goal)
	values
('1','administration','1','GCompris Administration Menu','Left-Click with the mouse to select an activity','','If you want to fine tune GCompris to your needs, you can use the administration module here. The ultimate goal is to provide child-specific reporting for parents and teacher who want to monitor the progress, strengths and needs of their children.'),
('2','advanced_colors','6','Advanced colors','Click on the correct color','Can read','Learn to recognize unusual colors.'),
('3','algebramenu','0','Go to calculation activities','Various calculation activities.','',''),
('4','algebra_by','3','Practice the multiplication operation','Answer some algebra questions','Multiplication table','In a limited time, give the product of two numbers'),
('5','algebra_group','0','Go to Algebra activities','Left-click the mouse on an activity to select it.','',''),
('6','algebra_guesscount','3','Find the series of correct operations that matches the given answer','Work out the right combination of numbers and operations to match the given value','The four arithmetic operations. Combine several arithmetic operations.','Deploy a strategy to arrange a set of arithmetic operations to match a given value.'),
('7','algebra_minus','2','Practice the subtraction operation','Answer some algebra questions','Simple subtraction','In a limited time, find the difference between two numbers'),
('8','algebra_plus','1','Practice the addition operation','Answer some algebra questions','Simple addition. Can recognize written numbers','In a limited time, find the sum of of two numbers. Introduction to simple in-line addition.'),
('9','algorithm','2','algorithm','Complete a list of symbols','Move and click the mouse','Logic training activity'),
('10','anim','3','Create a drawing or an animation','Free drawing and animation tool.','Needs to be capable of moving and clicking the mouse easily','In this game, children can draw freely. The goal is to discover how to create attractive drawings based on basic shapes: rectangles, ellipses and lines. To give children a wider range of choices, a set of images can also be used.'),
('11','awele','2','Oware','Play the Oware strategy game against Tux','','The object of the game is to capture more seeds than one''s opponent. Since the game has only 48 seeds, capturing 25 is sufficient to accomplish this. Since there are an even number of seeds, it is possible for the game to end in a draw, where each player has captured 24. The game is over when one player has captured 25 or more seeds, or both players have taken 24 seeds each (draw). If both players agree that the game has been reduced to an endless cycle, each player captures the seeds on their side of the board.'),
('12','babymatch','1','Matching Items','Drag and Drop the items to make them match','Mouse manipulation: movement, drag and drop. Cultural references.','Motor coordination. Conceptual matching.'),
('13','babyshapes','1','Complete the puzzle','Drag and Drop the shapes on their respective targets','Good mouse-control',''),
('14','ballcatch','1','Make the ball go to Tux','Press the two shift keys at the same time, to make the ball go in a straight line.','',''),
('15','bargame','2','bar game','Don''t use the last ball','Brain','Logic-training activity'),
('16','billard','1','The football game','Kick the ball into the goal','Mouse-manipulation','Kick the ball into the black hole on the right'),
('17','braille','0','Discover the Braille system','The Braille system is a method that is widely used by blind people to read and write, and was the first digital form of writing.','',''),
('18','braille_alphabets','5','Discover the Braille system','Learn and memorize the Braille system.','','Let kids discover the Braille system.'),
('19','braille_fun','6','Braille Fun','Braille the falling letters','Braille Alphabet Codes',''),
('20','braille_lotto','6','Braille Lotto','Discover the Braille system for numbers.','',''),
('21','canal_lock','2','Operate a canal lock','Tux is in trouble, and needs to take his boat through a lock. Help Tux and find out how a canal lock works.','',''),
('22','chat','3','Chat and draw with your friends','This chat activity only works on the local network','',''),
('23','chess','0','Practice chess','Play chess against the computer in a learning mode','',''),
('24','chess_computer','2','Learning chess','Play chess against the computer in a learning mode','Mouse-manipulation',''),
('25','chess_movelearn','2','Learning chess','Chess training. Catch the computer''s pawns.','Mouse-manipulation',''),
('26','chess_partyend','2','Learning chess','Play the end of the chess game against the computer','Mouse-manipulation',''),
('27','chronos','1','Chronos','Drag and Drop the items to organize the story','Tell a short story','Sort the pictures into the order that tells the story'),
('28','clickanddraw','2','Click and draw','Draw the picture by clicking on the blue points.','',''),
('29','clickgame','1','Click On Me','Left-Click with the mouse on all the swimming fish before they leave the fishtank','Mouse-manipulation','Motor coordination: moving and clicking the mouse.'),
('30','click_on_letter','1','Click on a lowercase letter','Listen to a letter and click on the right one','Visual letter-recognition. Can move the mouse.','Letter-name recognition'),
('31','click_on_letter_up','1','Click on an uppercase letter','Listen to a letter and click on the right one','Visual letter-recognition. Can move the mouse.','Letter-name recognition'),
('32','clockgame','2','Learning Clock','Learn how to tell the time','The concept of time. Reading the time.','Distinguish between time-units (hour, minute and second). Set and display time on a clock.'),
('33','colors','1','Colors','Click on the right color','Can move the mouse.','This board teaches you to recognize different colors. When you hear the name of the color, click on the duck wearing it.'),
('34','colors_group','0','Go to Color activities','Colors based activities.','',''),
('35','computer','0','Discover the Computer','Play with computer peripherals.','',''),
('36','connect4-2players','2','Connect 4 (2 Players)','Arrange four coins in a row','Mouse-manipulation','Create a line of 4 pieces either horizontally (lying down) or vertically (standing up) or diagonally.'),
('37','connect4','2','Connect 4','Arrange four coins in a row','Mouse-manipulation','Create a line of 4 pieces either horizontally (lying down), vertically (standing up) or diagonally.'),
('38','crane','2','Build the same model','Drive the crane and copy the model','Mouse manipulation','Motor-coordination'),
('39','details','2','Find the details','Drag and Drop the shapes on their respective targets','Good mouse-control',''),
('40','discovery','0','Go to discovery activities','Colors, sounds, memory...','',''),
('41','doubleentry','2','Double-entry table','Drag and Drop the items in the double-entry table','Basic counting skills','Move the items on the left to their proper position in the double-entry table.'),
('42','draw','2','A simple vector-drawing tool','A creative board where you can draw freely','Needs to be capable of moving and clicking the mouse easily','In this game, children can draw freely. The goal is to discover how to create attractive drawings based on basic shapes: rectangles, ellipses and lines.'),
('43','drawnumber','4','Draw Number','Draw the picture by following numbers','Can count from 1 to 50.',''),
('44','electric','5','Electricity','Create and simulate an electric schema','Requires some basic understanding of the concept of electricity.','Freely create an electric schema with a real time simulation of it.'),
('45','enumerate','1','Count the items','Place the items in the best way to count them','Basic enumeration','Numeration training'),
('46','erase','1','Move the mouse','Move the mouse to erase the area and discover the background','Mouse-manipulation','Motor-coordination'),
('47','erase_2clic','2','Double click the mouse','Double click the mouse to erase the area and discover the background','Mouse-manipulation','Motor-coordination'),
('48','erase_clic','1','Click the mouse','Click the mouse to erase the area and discover the background','Mouse-manipulation','Motor-coordination'),
('49','experience','0','Go to experiential activities','Various activities based on physical movement.','',''),
('50','experimental','0','Go to Experimental activities','Run gcompris --experimental to see this menu.','',''),
('51','fifteen','5','The fifteen game','Move each item to make an increasing series: from the smallest to the largest','Mouse-manipulation',''),
('52','followline','1','Control the hose-pipe','Tux needs to water the flowers, but the hose is blocked.','','Fine motor coordination'),
('53','fun','0','Go to Amusement activities','Various fun activities.','',''),
('54','geography','2','Locate the countries','Drag and Drop the items to redraw the whole map','Mouse manipulation: movement, drag and drop',''),
('55','geometry','0','Geometry','Geometry activities.','',''),
('56','geo_country','2','Locate the region','Drag and Drop the regions to redraw the whole country','Mouse manipulation: movement, drag and drop',''),
('57','gletters','1','Simple Letters','Type the falling letters before they reach the ground','Keyboard manipulation','Letter association between the screen and the keyboard'),
('58','gnumch-equality','3','Equality Number Munchers','Guide the Number Muncher to the expressions that equal the number at the top of the screen.','','Practice addition, multiplication, division and subtraction.'),
('59','gnumch-factors','5','Factor Number Munchers','Guide the Number Muncher to all the factors of the number at the top of the screen.','','Learn about factors and multiples.'),
('60','gnumch-inequality','3','Inequality Number Munchers','Guide the Number Muncher to the all the expressions that do not equal the number at the top of the screen.','','Practice addition, subtraction, multiplication and division.'),
('61','gnumch-multiples','3','Multiple Number Munchers','Guide the Number Muncher to all the multiples of the number at the top of the screen.','','Learn about multiples and factors.'),
('62','gnumch-primes','6','Prime Number Munchers','Guide the Number Muncher to all the prime numbers.','','Learn about prime numbers'),
('63','gnumchmenu','0','Go to Number Munchers activities','Number Munchers are games to play with arithmetic.','',''),
('64','guessnumber','3','Guess a number','Help Tux escape the cave. Tux hides a number for you to find.','Numbers from 1 to 1000 for the last level.',''),
('65','hangman','5','The classic hangman game','A word is hidden, you must discover it letter by letter','Reading skill','This is a good exercise to improve reading and spelling skills.'),
('66','hanoi','2','Simplified Tower of Hanoi','Reproduce the given tower','Mouse-manipulation','Reproduce the tower on the right in the empty space on the left'),
('67','hanoi_real','3','The Tower of Hanoi','Reproduce the tower on the right side','Mouse manipulation','The object of the game is to move the entire stack to another peg, obeying the following rules:
* only one disc may be moved at a time
* no disc may be placed atop a smaller disc'),
('68','hexagon','2','hexagon','Find the strawberry by clicking on the blue fields','Move and click the mouse','Logic-training activity'),
('69','hydroelectric','4','Learn about an electrical system based on renewable energy','Tux has come back from a long fishing party on his boat. Bring the electrical system back up so he can have light in his home.','','Learn about an electrical system based on renewable energy'),
('70','imageid','2','Reading practice','Practice reading by finding the word matching an image','Reading',''),
('71','imagename','3','Image Name','Drag and Drop each item above its name','Reading','Vocabulary and reading'),
('72','instruments','4','Music instruments','Click on the correct musical instruments','','Learn to recognize musical instruments.'),
('73','keyboard','0','Keyboard-manipulation boards','Discover the keyboard.','',''),
('74','lang','3','Practice a foreign language','Practice a foreign language','',''),
('75','leftright','1','Find your left and right hands','Determine if a hand is a right or a left hand','None','Distinguish right and left hands from different points of view. Spatial representation'),
('76','lightsoff','6','Lights Off','The aim is to switch off all the lights.','','The aim is to switch off all the lights.'),
('77','login','0','GCompris login screen','Select or enter your name to log in to GCompris','','GCompris identifies each child, so we can provide child-specific reports.'),
('78','louis_braille','4','The History of Louis Braille','Review the major dates of the inventor of the Braille system.','',''),
('79','magic_hat_minus','2','The magician hat','Count how many items are under the magic hat after some have got away','Subtraction','Learn subtraction'),
('80','magic_hat_plus','2','The magician hat','Count how many items are under the magic hat','Addition','Learn addition'),
('81','math','0','Mathematics','Mathematical activities.','',''),
('82','maze','2','Maze','Find your way out of the maze','Can use the keyboard arrow to move an object.','Help Tux get out of this maze.'),
('83','maze2DRelative','3','Maze','Find your way out of the maze (Move is relative)','Can use the keyboard arrow to move an object.','Help Tux get out of this maze.'),
('84','maze3D','2','3D Maze','Find your way out of the 3D maze','Can use the keyboard arrow to move an object.','Help Tux get out of this maze.'),
('85','mazeInvisible','4','Maze','Find your way out of the invisible maze','Can use the keyboard arrow to move an object.','Help Tux get out of this maze.'),
('86','mazeMenu','0','Go to Maze activities','Find your way out of different types of mazes','',''),
('87','melody','2','Melody','Repeat a melody','Move and click the mouse','Ear-training activity'),
('88','memory','1','Memory Game with images','Flip the cards to find the matching pairs','Mouse-manipulation','Train your memory and remove all the cards'),
('89','memory_add','1','Addition memory game','Turn the cards over to find two numbers which add up the same, until all the cards are gone.','Addition','Practise adding up, until all the cards are gone.'),
('90','memory_add_minus','1','Addition and subtraction memory game','Turn the cards over to find two numbers which add or subtract the same, until all the cards are gone.','Addition and subtraction','Practise addition, subtraction, until all the cards are gone.'),
('91','memory_add_minus_mult_div','1','All operations memory game','Turn the cards over to find a matching operation, until all the cards are gone.','Addition, subtraction, multiplication, division','Practise addition, subtraction, multiplication, division, until all the cards are gone.'),
('92','memory_add_minus_mult_div_tux','1','All operations memory game against Tux','Turn the cards over to find a matching operation, until all the cards are gone.','Addition, subtraction, multiplication, division','Practise addition, subtraction, multiplication, division, until all the cards are gone.'),
('93','memory_add_minus_tux','1','Addition and subtraction memory game against Tux','Turn the cards over to find two numbers which add or subtract the same, until all the cards are gone.','Addition and subtraction','Practise addition, subtraction, until all the cards are gone.'),
('94','memory_add_tux','1','Addition memory game against Tux','Turn the cards over to find two numbers which add up the same, until all the cards are gone.','Additions','Practise adding up, until all the cards are gone.'),
('95','memory_div','1','Division memory game','Turn the cards over to find a matching operation, until all the cards are gone.','Division','Practise division, until all the cards are gone.'),
('96','memory_div_tux','1','Division memory game against Tux','Turn the cards over to find a matching operation, until all the cards are gone.','Division','Practise division, until all the cards are gone.'),
('97','memory_enumerate','1','Enumeration memory game','Turn the cards over to match the number with the drawn picture.','Addition','Numeration training, memory.'),
('98','memory_group','0','Go to Memory activities','Various memory activities (images, letters, sounds).','',''),
('99','memory_minus','1','Subtraction memory game','Turn the cards over to find two numbers which subtract the same, until all the cards are gone.','Subtraction','Practise subtraction, until all the cards are gone.'),
('100','memory_minus_tux','1','Subtraction memory game against Tux','Turn the cards over to find two numbers which subtract the same, until all the cards are gone.','Subtraction','Practise subtraction, until all the cards are gone.'),
('101','memory_mult','1','Multiplication memory game','Turn the cards over to find two numbers which multiply the same, until all the cards are gone.','Multiplication','Practise multiplication, until all the cards are gone.'),
('102','memory_mult_div','1','Multiplication and division memory game','Turn the cards over to find a matching operation, until all the cards are gone.','Multiplication, division','Practise multiplication, division, until all the cards are gone.'),
('103','memory_mult_div_tux','1','Multiplication and division memory game against Tux','Turn the cards over to find a matching operation, until all the cards are gone.','Multiplication, division','Practise multiplication, division, until all the cards are gone.'),
('104','memory_mult_tux','1','Multiplication memory game against Tux','Turn the cards over to find a matching operation, until all the cards are gone.','Additions','Practise multiplication until all the cards are gone.'),
('105','memory_op_group','0','Go to mathematics memory activities','Memory activities based on operations','',''),
('106','memory_op_group_tux','0','Go to mathematics memory activities against Tux','Memory activities based on operations','',''),
('107','memory_sound','1','Audio memory game','Click on Tux the violinist and listen to find the matching sounds','Mouse manipulation, Brain.','Train your audio memory and remove all the violonists Tux.'),
('108','memory_sound_tux','2','Audio memory game against Tux','Play the audio memory game against Tux','Mouse manipulation, Brain.','Train your audio memory and remove all the violonists Tux.'),
('109','memory_tux','2','Memory Game with images, against Tux','Have a memory competition with Tux.','Mouse manipulation, Brain.','Train your memory and remove all the cards'),
('110','memory_wordnumber','1','Wordnumber memory game','Turn the cards over to match the number with the word matching it.','Reading','Reading numbers, memory.'),
('111','','0','GCompris Main Menu','Left-click the mouse on an activity to select it.','GCompris is a collection of educational games that provides different activities for children aged 2 and up.','The goal of GCompris is to provide a free alternative to popular proprietary edutainment software'),
('112','miscelaneous','0','Miscellaneous activities','Time, Geography, ...','',''),
('113','missing_letter','2','Missing Letter','Fill in the missing letter','Word reading','Training reading skills'),
('114','money','2','Money','Practice money usage','Can count','You must buy the different items and give the exact price. At higher levels, several items are displayed, and you must first calculate the total price.'),
('115','money_back','3','Give tux his change','Practice money usage by giving Tux his change','Can count','Tux bought you different items and shows you his money. You must give him back his change. At higher levels, several items are displayed, and you must first calculate the total price.'),
('116','money_back_cents','5','Give tux his change, including cents','Practice money usage by giving Tux his change','Can count','Tux bought you different items and shows you his money. You must give him back his change. At higher levels, several items are displayed, and you must first calculate the total price.'),
('117','money_cents','5','Money','Practice money usage including cents','Can count','You must buy the different items and give the exact price. At higher levels, several items are displayed, and you must first calculate the total price.'),
('118','money_group','0','Go to money activities','Left-click the mouse on an activity to select it.','',''),
('119','mosaic','1','Rebuild the mosaic','Rebuild the mosaic','',''),
('120','mouse','0','Mouse-manipulation activities.','Various mouse-based activities (clicking, moving)','',''),
('121','numeration','0','Numeration','Numeration activities.','',''),
('122','paintings','1','Assemble the puzzle','Drag and Drop the items to rebuild the original paintings','Mouse-manipulation: movement, drag and drop','Spatial representation'),
('123','paratrooper','1','Parachutist','Help Tux the parachutist land safely','This board is game-oriented. No specific skills are needed to play.','In this game, Tux the parachutist needs help to land safely on the fishing boat. He needs to allow for the wind direction and speed.'),
('124','penalty','2','Penalty kick','Double click the mouse on the ball to score a goal.','Mouse-manipulation','Motor-coordination'),
('125','photohunter','2','Photo hunter','Find the differences between two pictures','','Visual discrimination.'),
('126','planegame','2','Numbers in Order','Move the helicopter to catch the clouds in the correct order','Number','Numeration training'),
('127','puzzle','0','Puzzles','Various puzzles.','',''),
('128','pythontemplate','1','Python Template','An empty python activity to use as a starting point','Advanced Python Programmer :)','Add a language-binding to GCompris.'),
('129','pythontest','1','Python Test','Test board for the python plugin','Advanced Python Programmer :)','Add a language-binding to GCompris.'),
('130','railroad','1','Railway','A memory game based on trains','None','Memory-training'),
('131','reading','0','Go to the Reading activities','Reading activities.','',''),
('132','readingh','2','Horizontal reading practice','Read a list of words and work out if a given word is in it','Reading','Reading training in a limited time'),
('133','readingv','2','Vertical-reading practice','Read a vertical list of words and work out if a given word is in it','Reading','Read training in a limited time'),
('134','redraw','3','Redraw the given item','Copy a drawing from the box on the right into the box on the left.','','Copy a drawing from the box on the right into the box on the left.'),
('135','redraw_symmetrical','4','Mirror the given item','Copy the mirror image of an object from the box on the right into the box on the left.','','Copy the mirror image of an object from the box on the right into the box on the left.'),
('136','reversecount','2','Practice subtraction with a fun game','Tux is hungry. Help him find fish by counting to the correct ice spot.','Can move the mouse, can read numbers and subtract numbers up to 10 for the first level','Tux is hungry. Help him find fish by counting to the correct ice spot.'),
('137','scalesboard','2','Balance the scales properly','Drag and Drop weights to balance the scales','','Mental calculation, arithmetic equality'),
('138','scalesboard_weight','4','Balance the scales properly','Drag and Drop masses to balance the scales and calculate the weight','','Mental calculation, arithmetic equality, unit conversion'),
('139','searace','6','Sea race (2 Players)','Direct your boat accurately to win the race.','','In this activity, you will learn how to enter commands into a computer. Even if the language is extremely basic, you learn here how to think ahead and construct a program. This activity can be used to introduce the programming concept to children.'),
('140','searace1player','6','Sea race (Single Player)','Give good instructions to your ship in order to be first in the race.','','In this activity, you will learn how to enter commands into a computer. Even if the language is extremely basic, you learn here how to think ahead and construct a program. This activity can be used to introduce the programming concept to children.'),
('141','smallnumbers','1','Numbers With Dice','Count the number of dots on dice before they reach the ground','Counting skills','In a limited time, count the number of dots'),
('142','smallnumbers2','1','Numbers with pairs of dice','Count the number of dots on dice before they reach the ground','Counting skills','In a limited time, count the number of dots'),
('143','sound_group','0','Go to Sound activities','Sound based activities.','',''),
('144','strategy','0','Strategy games','Strategy games like chess, connect4, ...','',''),
('145','submarine','5','Pilot a submarine','Pilot a submarine using air tanks and dive rudders','Physics basics','Learn how a submarine works'),
('146','sudoku','4','Sudoku, place unique symbols in a square.','Symbols must be unique in a row, in a column, and (if defined) each region.','Completing the puzzle requires patience and logical ability','The aim of the puzzle is to enter a symbol or numeral from 1 through 9 in each cell of a grid, most frequently a 9x9 grid made up of 3x3 subgrids (called ''regions''), starting with various symbols or numerals given in some cells (the ''givens''). Each row, column and region must contain only one instance of each symbol or numeral (Source &lt;http://en.wikipedia.org/wiki/Sudoku&gt;).'),
('147','superbrain','2','Super Brain','Tux has hidden several items. Find them again in the correct order','','Tux has hidden several items. Find them again in the correct order'),
('148','tangram','1','The tangram puzzle game','The objective is to form a given shape with seven pieces','Mouse-manipulation','From Wikipedia, the free encyclopedia. Tangram (Chinese: literally ""seven boards of cunning"") is a Chinese puzzle. While the tangram is often said to be ancient, its existence has only been verified as far back as 1800. It consists of 7 pieces, called tans, which fit together to form a square; taking the square as the unit:
	* 5 right isosceles triangles
		o 2 small (legs of 1)
		o 1 medium size (legs of square root of 2)
		o 2 large size (legs of 2)
	* 1 square (side of 1)
	* 1 parallelogram (sides of 1 and square root of 2)'),
('149','target','2','Practice addition with a target game','Hit the target and count your points','Can move the mouse, can read numbers and count up to 15 for the first level','Throw darts at a target and count your score.'),
('150','traffic','2','A sliding-block puzzle game','Remove the red car from the parking lot through the gate on the right','','Remove the red car from the parking lot through the gate on the right'),
('151','watercycle','3','Learn about the water cycle','Tux has come back from a long fishing party on his boat. Bring the water system back up so he can take a shower.','','Learn the water cycle'),
('152','wordprocessor','2','Your word processor','A simple word processor to enter and save any text','The children can type their own text or copy one given by the teacher.','Learn how to enter text in a wordprocessor. This wordprocessor is special in that it enforces the use of styles. This way, the children will understand their benefit when moving to more feature full wordprocessor like OpenOffice.org.'),
('153','wordsgame','2','Falling Words','Type the falling words before they reach the ground','Keyboard manipulation','Keyboard training')


-- verify data

Select * from boards